name: osc_thesis

channels:
  - default
  - pytorch
  - nvidia

dependencies:
  - python=3.10
  - pandas>=1.4.3
  - numpy>=1.22.3
  - matplotlib>=3.5.2
  - pytorch-cuda>=1.11.0
  - torchvision>=0.12.0
  - tqdm>=4.64.0
  - pyyaml
  - pip
  - tensorboard
  - pip:
      - https://github.com/Vastlab/vast/archive/63-network-architectures-include-bias-neuron-in-the-last-layer.zip
